server:
  servlet:
    context-path: /message-logging-service
  error:
    include-message: always

spring:
  application:
    name: Logging service
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:test;mode=Oracle
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
